# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-16 08:34
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussdke', '0002_auto_20160305_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=b'icon'),
        ),
    ]
