# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdke', '0003_auto_20160516_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isSuggestion',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='ussd',
            name='isSuggestion',
            field=models.BooleanField(default=1),
        ),
    ]
