# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-11 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussdke', '0004_auto_20160805_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invalidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('checked', models.BooleanField(default=False)),
                ('ussd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussdke.USSD')),
            ],
        ),
    ]
