# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdke', '0005_invalidation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
