# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ussdke', '0006_auto_20160811_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 28, 14, 28, 29, 924826, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 28, 14, 28, 39, 993227, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invalidation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invalidation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ussd',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ussd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
